// Helplines Search API endpoint




const helplines = [
  {
    id: "113-suicide",
    name: "113 Zelfmoordpreventie",
    description: "Suicide prevention hotline available 24/7",
    descriptionNl: "Zelfmoordpreventielijn, 24 uur per dag, 7 dagen per week bereikbaar",
    phone: "113",
    website: "https://www.113.nl",
    categoryId: "mental-health",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands", "Engels"],
    isEmergency: true,
    isFeatured: true,
  },
  {
    id: "sensoor",
    name: "SenSoor",
    description: "Support for people with autism and ADHD",
    descriptionNl: "Ondersteuning voor autistische personen en ADHD",
    phone: "088 - 0020000",
    website: "https://www.sensoor.nl",
    categoryId: "mental-health",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: true,
  },
  {
    id: "korrelatie",
    name: "Korrelatie",
    description: "Mental health support and counseling",
    descriptionNl: "Ondersteuning en begeleiding voor geestelijke gezondheid",
    phone: "030 - 2733500",
    website: "https://www.korrelatie.nl",
    categoryId: "mental-health",
    hoursNl: "Ma-vr 09:00-17:30",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: true,
  },
  {
    id: "centrum-seksueel-geweld",
    name: "Centrum Seksueel Geweld",
    description: "Support for victims of sexual violence",
    descriptionNl: "Ondersteuning voor slachtoffers van seksueel geweld",
    phone: "088 - 4616666",
    website: "https://www.centrumseksueelgeweld.nl",
    categoryId: "abuse-violence",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands", "Engels"],
    isEmergency: true,
    isFeatured: false,
  },
  {
    id: "veilig-thuis",
    name: "Veilig Thuis",
    description: "Support for domestic violence and child abuse",
    descriptionNl: "Ondersteuning bij huiselijk geweld en kindermishandeling",
    phone: "0800 - 2000",
    website: "https://www.veiligthuis.nl",
    categoryId: "abuse-violence",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: true,
    isFeatured: true,
  },
  {
    id: "kindertelefoon",
    name: "Kindertelefoon",
    description: "Helpline for children aged 6-18",
    descriptionNl: "Hulplijn voor kinderen van 6-18 jaar",
    phone: "0800 - 0432",
    website: "https://www.kindertelefoon.nl",
    categoryId: "child-family",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: true,
  },
  {
    id: "bureau-jeugdzorg",
    name: "Bureau Jeugdzorg",
    description: "Youth care and family support services",
    descriptionNl: "Jeugdzorg en ondersteuning voor gezinnen",
    phone: "0900 - 1239",
    website: "https://www.bureaujeugdzorg.nl",
    categoryId: "child-family",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "samen-tegen-kanker",
    name: "Samen Tegen Kanker",
    description: "Support for cancer patients and their families",
    descriptionNl: "Ondersteuning voor kankerpatiënten en hun families",
    phone: "0900 - 0170",
    website: "https://www.samentegenkanker.nl",
    categoryId: "health-medical",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "roken-stoppen",
    name: "Roken Stoppen",
    description: "Support for quitting smoking",
    descriptionNl: "Ondersteuning voor het stoppen met roken",
    phone: "0800 - 0199",
    website: "https://www.stivoro.nl",
    categoryId: "health-medical",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "alcoholics-anonymous-nl",
    name: "Anonyme Alcoholisten",
    description: "Support for alcohol addiction",
    descriptionNl: "Ondersteuning voor alcoholverslaving",
    phone: "0900 - 0700",
    website: "https://www.aanl.nl",
    categoryId: "addiction",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "drugs-info",
    name: "Drugs Info",
    description: "Information and support for drug use",
    descriptionNl: "Informatie en ondersteuning bij drugsgebruik",
    phone: "020 - 3200333",
    website: "https://www.drugsinfo.nl",
    categoryId: "addiction",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "coa-nl",
    name: "COA",
    description: "Support for refugees and asylum seekers",
    descriptionNl: "Ondersteuning voor asielzoekers en vluchtelingen",
    phone: "088 - 0020000",
    website: "https://www.coa.nl",
    categoryId: "immigration",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands", "Engels"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "gay-nc",
    name: "Gay NC",
    description: "LGBTQ+ support and community services",
    descriptionNl: "LGBTQ+ ondersteuning en gemeenschapsdiensten",
    phone: "020 - 4221020",
    website: "https://www.gaync.nl",
    categoryId: "lgbtq",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands", "Engels"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "lesbian-lgbtq",
    name: "Lesbian Support Network",
    description: "Support for lesbian and trans women",
    descriptionNl: "Ondersteuning voor lesbische en transvrouwen",
    phone: "088 - 0020000",
    website: "https://www.lgbtq-nl.org",
    categoryId: "lgbtq",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "feantsabnl",
    name: "FEANTSA NL",
    description: "Homelessness prevention and support services",
    descriptionNl: "Dakloosheidspreventie en ondersteuning",
    phone: "088 - 0020000",
    website: "https://www.feantsa.org",
    categoryId: "homelessness",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands", "Engels"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "shelter-overijssel",
    name: "Shelter Overijssel",
    description: "Emergency shelter and housing support",
    descriptionNl: "Noodopvang en huisvestingsondersteuning",
    phone: "088 - 1234567",
    website: "https://www.shelter-overijssel.nl",
    categoryId: "homelessness",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: true,
    isFeatured: false,
  },
  {
    id: "schuldhulp-nl",
    name: "Schuldhulp Nederland",
    description: "Debt counseling and financial support",
    descriptionNl: "Schuldhulp en financiële begeleiding",
    phone: "0900 - 0113",
    website: "https://www.schuldhulpnederland.nl",
    categoryId: "financial-debt",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "nibud",
    name: "NIBUD",
    description: "Financial advice and budgeting support",
    descriptionNl: "Financieel advies en begrotingsondersteuning",
    phone: "088 - 0020000",
    website: "https://www.nibud.nl",
    categoryId: "financial-debt",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "studiesteun",
    name: "Studiesteun",
    description: "Study guidance and education support",
    descriptionNl: "Studiebegeleiding en educatieve ondersteuning",
    phone: "020 - 5255000",
    website: "https://www.studiesteun.nl",
    categoryId: "education-career",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "arbeid-integratie",
    name: "Arbeid Integratie",
    description: "Career counseling and job placement services",
    descriptionNl: "Carrièrebegeleiding en arbeidsbemiddeling",
    phone: "088 - 0020000",
    website: "https://www.arbeidsintegratie.nl",
    categoryId: "education-career",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "ggd-nl",
    name: "GGD Nederland",
    description: "Public health services and medical support",
    descriptionNl: "Openbare gezondheid en medische ondersteuning",
    phone: "0900 - 0111",
    website: "https://www.ggd.nl",
    categoryId: "health-medical",
    hoursNl: "Ma-vr 08:00-18:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "artsen-zonder-grenzen",
    name: "Artsen Zonder Grenzen",
    description: "Medical humanitarian aid and support",
    descriptionNl: "Medische hulp zonder grenzen",
    phone: "088 - 0020000",
    website: "https://www.artsenzonergrenzen.nl",
    categoryId: "health-medical",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands", "Engels"],
    isEmergency: true,
    isFeatured: false,
  },
  {
    id: "victims-support",
    name: "Victim Support Netherlands",
    description: "Support for crime victims",
    descriptionNl: "Ondersteuning voor slachtoffers van misdrijven",
    phone: "088 - 0020000",
    website: "https://www.slachtofferhulp.nl",
    categoryId: "abuse-violence",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: false,
  },
  {
    id: "rape-crisis",
    name: "Rape Crisis Center",
    description: "Specialized support for sexual assault survivors",
    descriptionNl: "Gespecialiseerde ondersteuning voor seksuele agressie slachtoffers",
    phone: "088 - 4616666",
    website: "https://www.crisiscentrum.nl",
    categoryId: "abuse-violence",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands", "Engels"],
    isEmergency: true,
    isFeatured: false,
  },
  {
    id: "elder-abuse",
    name: "Elder Abuse Hotline",
    description: "Protection and support for elderly abuse victims",
    descriptionNl: "Bescherming en ondersteuning voor ouderenmishandeling slachtoffers",
    phone: "0800 - 0060",
    website: "https://www.ouderenmishandeling.nl",
    categoryId: "abuse-violence",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: true,
    isFeatured: false,
  },
];

export default function handler(req, res) {
  const query = req.query.query as string;
  
  if (!query) {
    return res.status(400).json({ error: "Query parameter required" });
  }
  
  const searchTerm = query.toLowerCase();
  const filtered = helplines.filter((h) => {
    return (
      h.name.toLowerCase().includes(searchTerm) ||
      h.description.toLowerCase().includes(searchTerm) ||
      h.descriptionNl.toLowerCase().includes(searchTerm) ||
      (h.phone && h.phone.includes(query))
    );
  });
  
  res.status(200).json(filtered);
}
