// Featured Helplines API endpoint
const helplines = [
  {
    id: "113-suicide",
    name: "113 Zelfmoordpreventie",
    description: "Suicide prevention hotline available 24/7",
    descriptionNl: "Zelfmoordpreventielijn, 24 uur per dag, 7 dagen per week bereikbaar",
    phone: "113",
    website: "https://www.113.nl",
    categoryId: "mental-health",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands", "Engels"],
    isEmergency: true,
    isFeatured: true,
  },
  {
    id: "sensoor",
    name: "SenSoor",
    description: "Support for people with autism and ADHD",
    descriptionNl: "Ondersteuning voor autistische personen en ADHD",
    phone: "088 - 0020000",
    website: "https://www.sensoor.nl",
    categoryId: "mental-health",
    hoursNl: "Ma-vr 09:00-17:00",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: true,
  },
  {
    id: "korrelatie",
    name: "Korrelatie",
    description: "Mental health support and counseling",
    descriptionNl: "Ondersteuning en begeleiding voor geestelijke gezondheid",
    phone: "030 - 2733500",
    website: "https://www.korrelatie.nl",
    categoryId: "mental-health",
    hoursNl: "Ma-vr 09:00-17:30",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: true,
  },
  {
    id: "veilig-thuis",
    name: "Veilig Thuis",
    description: "Support for domestic violence and child abuse",
    descriptionNl: "Ondersteuning bij huiselijk geweld en kindermishandeling",
    phone: "0800 - 2000",
    website: "https://www.veiligthuis.nl",
    categoryId: "abuse-violence",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: true,
    isFeatured: true,
  },
  {
    id: "kindertelefoon",
    name: "Kindertelefoon",
    description: "Helpline for children aged 6-18",
    descriptionNl: "Hulplijn voor kinderen van 6-18 jaar",
    phone: "0800 - 0432",
    website: "https://www.kindertelefoon.nl",
    categoryId: "child-family",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: false,
    isFeatured: true,
  },
];

export default function handler(req, res) {
  const featured = helplines.filter((h) => h.isFeatured);
  res.status(200).json(featured);
}
